# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Alex\Dropbox\Desenvolvimento\Python\ArtistTracker\designer\ArtistManagerUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ArtistManager(object):
	def setupUi(self, ArtistManager):
		ArtistManager.setObjectName("ArtistManager")
		ArtistManager.resize(594, 427)
		self.centralwidget = QtWidgets.QWidget(ArtistManager)
		self.centralwidget.setObjectName("centralwidget")
		self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
		self.gridLayout.setObjectName("gridLayout")
		self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
		self.tabWidget.setSizePolicy(sizePolicy)
		self.tabWidget.setObjectName("tabWidget")
		self.tab = QtWidgets.QWidget()
		self.tab.setObjectName("tab")
		self.listAlias = QtWidgets.QListWidget(self.tab)
		self.listAlias.setGeometry(QtCore.QRect(10, 90, 551, 221))
		self.listAlias.setIconSize(QtCore.QSize(50, 50))
		self.listAlias.setObjectName("listAlias")
		self.lineAliasName = QtWidgets.QLineEdit(self.tab)
		self.lineAliasName.setGeometry(QtCore.QRect(10, 320, 141, 20))
		self.lineAliasName.setObjectName("lineAliasName")
		self.lineAliasUrl = QtWidgets.QLineEdit(self.tab)
		self.lineAliasUrl.setGeometry(QtCore.QRect(160, 320, 171, 20))
		self.lineAliasUrl.setObjectName("lineAliasUrl")
		self.comboBoxServices = QtWidgets.QComboBox(self.tab)
		self.comboBoxServices.setGeometry(QtCore.QRect(340, 320, 141, 22))
		self.comboBoxServices.setObjectName("comboBoxServices")
		self.pushSaveAlias = QtWidgets.QPushButton(self.tab)
		self.pushSaveAlias.setGeometry(QtCore.QRect(490, 320, 31, 23))
		self.pushSaveAlias.setObjectName("pushSaveAlias")
		self.pushRemoveAlias = QtWidgets.QPushButton(self.tab)
		self.pushRemoveAlias.setGeometry(QtCore.QRect(530, 320, 31, 23))
		self.pushRemoveAlias.setObjectName("pushRemoveAlias")
		self.labelName = QtWidgets.QLabel(self.tab)
		self.labelName.setGeometry(QtCore.QRect(10, 10, 27, 16))
		self.labelName.setObjectName("labelName")
		self.pushDelete = QtWidgets.QPushButton(self.tab)
		self.pushDelete.setEnabled(True)
		self.pushDelete.setGeometry(QtCore.QRect(530, 10, 32, 23))
		self.pushDelete.setMaximumSize(QtCore.QSize(32, 32))
		self.pushDelete.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.pushDelete.setFlat(True)
		self.pushDelete.setObjectName("pushDelete")
		self.label = QtWidgets.QLabel(self.tab)
		self.label.setGeometry(QtCore.QRect(10, 64, 33, 16))
		self.label.setObjectName("label")
		self.lineName = QtWidgets.QLineEdit(self.tab)
		self.lineName.setGeometry(QtCore.QRect(10, 30, 141, 20))
		self.lineName.setObjectName("lineName")
		self.tabWidget.addTab(self.tab, "")
		self.tab_1 = QtWidgets.QWidget()
		self.tab_1.setObjectName("tab_1")
		self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_1)
		self.gridLayout_2.setObjectName("gridLayout_2")
		self.gridLayout_3 = QtWidgets.QGridLayout()
		self.gridLayout_3.setObjectName("gridLayout_3")
		self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_2.setObjectName("horizontalLayout_2")
		self.verticalLayout_4 = QtWidgets.QVBoxLayout()
		self.verticalLayout_4.setObjectName("verticalLayout_4")
		self.label_2 = QtWidgets.QLabel(self.tab_1)
		self.label_2.setObjectName("label_2")
		self.verticalLayout_4.addWidget(self.label_2)
		self.pushSelectAvatar = QtWidgets.QPushButton(self.tab_1)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushSelectAvatar.sizePolicy().hasHeightForWidth())
		self.pushSelectAvatar.setSizePolicy(sizePolicy)
		self.pushSelectAvatar.setObjectName("pushSelectAvatar")
		self.verticalLayout_4.addWidget(self.pushSelectAvatar)
		spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
		self.verticalLayout_4.addItem(spacerItem)
		self.horizontalLayout_2.addLayout(self.verticalLayout_4)
		self.verticalLayout_3 = QtWidgets.QVBoxLayout()
		self.verticalLayout_3.setObjectName("verticalLayout_3")
		self.labelAvatar = QtWidgets.QLabel(self.tab_1)
		self.labelAvatar.setMinimumSize(QtCore.QSize(192, 192))
		self.labelAvatar.setMaximumSize(QtCore.QSize(192, 192))
		self.labelAvatar.setText("")
		self.labelAvatar.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
		self.labelAvatar.setObjectName("labelAvatar")
		self.verticalLayout_3.addWidget(self.labelAvatar, 0, QtCore.Qt.AlignRight)
		spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
		self.verticalLayout_3.addItem(spacerItem1)
		self.horizontalLayout_2.addLayout(self.verticalLayout_3)
		self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
		self.gridLayout_2.addLayout(self.gridLayout_3, 0, 0, 1, 1)
		self.tabWidget.addTab(self.tab_1, "")
		self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
		self.horizontalLayout = QtWidgets.QHBoxLayout()
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.pushSave = QtWidgets.QPushButton(self.centralwidget)
		self.pushSave.setMaximumSize(QtCore.QSize(100, 16777215))
		self.pushSave.setObjectName("pushSave")
		self.horizontalLayout.addWidget(self.pushSave)
		self.pushCancel = QtWidgets.QPushButton(self.centralwidget)
		self.pushCancel.setMaximumSize(QtCore.QSize(100, 16777215))
		self.pushCancel.setObjectName("pushCancel")
		self.horizontalLayout.addWidget(self.pushCancel)
		self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
		ArtistManager.setCentralWidget(self.centralwidget)

		self.retranslateUi(ArtistManager)
		self.tabWidget.setCurrentIndex(0)
		QtCore.QMetaObject.connectSlotsByName(ArtistManager)

	def retranslateUi(self, ArtistManager):
		_translate = QtCore.QCoreApplication.translate
		ArtistManager.setWindowTitle(_translate("ArtistManager", "Artist"))
		self.lineAliasName.setPlaceholderText(_translate("ArtistManager", "New Alias"))
		self.lineAliasUrl.setPlaceholderText(_translate("ArtistManager", "URL (optional)"))
		self.pushSaveAlias.setText(_translate("ArtistManager", "+"))
		self.pushRemoveAlias.setText(_translate("ArtistManager", "-"))
		self.labelName.setText(_translate("ArtistManager", "Name"))
		self.pushDelete.setText(_translate("ArtistManager", "-"))
		self.label.setText(_translate("ArtistManager", "Aliases"))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ArtistManager", "Artist"))
		self.label_2.setText(_translate("ArtistManager", "Avatar"))
		self.pushSelectAvatar.setText(_translate("ArtistManager", "Select File..."))
		self.pushSelectAvatar.setProperty("class", _translate("ArtistManager", "default"))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("ArtistManager", "Avatar"))
		self.pushSave.setText(_translate("ArtistManager", "Save"))
		self.pushSave.setProperty("class", _translate("ArtistManager", "primary"))
		self.pushCancel.setText(_translate("ArtistManager", "Close"))
		self.pushCancel.setProperty("class", _translate("ArtistManager", "default"))


if __name__ == "__main__":
	import sys
	app = QtWidgets.QApplication(sys.argv)
	ArtistManager = QtWidgets.QMainWindow()
	ui = Ui_ArtistManager()
	ui.setupUi(ArtistManager)
	ArtistManager.show()
	sys.exit(app.exec_())
